version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: botdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d botdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  bot:
    image: bot:1.0
    container_name: bot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/botdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update # или validate для продакшена
      SPRING_SQL_INIT_MODE: always # для инициализации данных
      TZ: Europe/Moscow # временная зона
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/workspace/logs
      - ./config:/config:ro # для дополнительных конфигов
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge